### ISSUE TITLE
start Lane detection by reading images.

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/lane_detection_opencv#1]
This is your first task,
You can use iPython notebook
first read the images using opencv and then show that image.
Make your PR for that.

**Comment by bharath-acchu** [comment]
Can I take this?

**Comment by akshitagupta15june** [comment]
what are you asking?

**Comment by bharath-acchu** [comment]
can I take up this issue?

**Comment by akshitagupta15june** [comment]
Yes ofcourse!

**Comment by akshitagupta15june** [comment]
Great work @bharath-acchu

**Comment by ashwanisng** [comment]
Is this pr is closed now or we can contribute?

**Comment by Anujg935** [comment]
Done by @ashwanisng
