### ISSUE TITLE
Applying Hough Transforms

### ISSUE THREAD

**Issue by bharath-acchu** [akshitagupta15june/lane_detection_opencv#17]
To the point, we now do not need to solve for a line that intersects all nearby edge pixels. Instead, we can simply solve for the intersections between lines in **Hough Space, and transform** that intersection point back into Image Space to obtain a line which intersects enough edge pixels. Fortunately for us, OpenCV ships with a function for generating Hough lines from an image containing edge pixels.

**The task is**  to use **hough transorms** to detect lines and **render the detected hough lines as an overlay**. 🙌

**Comment by Anujg935** [comment]
Hi, @bharath-acchu great issue to work on. I have assigned this issue to you. you can start working on this.
