### ISSUE TITLE
Display lane lines

### ISSUE THREAD

**Issue by vaani787** [akshitagupta15june/lane_detection_opencv#19]
Display the detected lane lines as an overlay on the original image of the road.

**Comment by Anujg935** [comment]
Actually same kind of issue is already posted by @bharath-acchu  so if you can do something different then let me know.

**Comment by vaani787** [comment]
Okay.

**Comment by Anujg935** [comment]
Hi @vaani787 You can work on this issue I reopened it. You can learn and complete this task and make PR. You will be evaluated for this issue also but may not be merged as its already done by another participant we will look int it about merging. For now, keep going with the issue.
