### ISSUE TITLE
 Road Lane Line Detection

### ISSUE THREAD

**Issue by ashwanisng** [akshitagupta15june/lane_detection_opencv#22]
Detecting Road lane line from an image. @Anujg935

**Comment by Anujg935** [comment]
Hi @ashwanisng You can work on this issue. You can learn and complete this task and make PR. You will be evaluated for this issue also but may not be merged as its already done by another participant we will look into it about merging. For now, keep going with the issue.

**Comment by akshitagupta15june** [comment]
@ashwanisng work in this issue and try to find some more different issue which will give our project a new shape.
