### ISSUE TITLE
Fill The area b/w lanes

### ISSUE THREAD

**Issue by Anujg935** [akshitagupta15june/lane_detection_opencv#24]
Hi everyone,
Here is a new task. I hope all of you are done with lane detection. Now the task is to fill the area b/w the detected lane lines with some other color. So as to make it a little more interesting.

Everyone can work on this issue everyone will be evaluated. No specific assignment to any participant will be done for this issue.

**Comment by Preetesh21** [comment]
Hey can I work on this issue?

**Comment by akshitagupta15june** [comment]
yes ofcourse
