### ISSUE TITLE
Camera calibration and distortion calculation

### ISSUE THREAD

**Issue by bharath-acchu** [akshitagupta15june/lane_detection_opencv#34]
**Task:** Compute the camera calibration matrix and distortion coefficients given a set of chessboard images/curved road lane images.

**_hint:_** OpenCV provide some really helpful built-in functions for the task on camera calibration. First of all, to detect the calibration pattern in the calibration images, we can use the function **`cv2.findChessboardCorners(image, pattern_size).`**

Once we have stored the correspondeces between 3D world and 2D image points for a bunch of images, we can proceed to actually calibrate the camera through **`cv2.calibrateCamera().`** Among other things, this function returns both the camera matrix and the distortion coefficients, which we can use to undistort the frames.

**Comment by Anujg935** [comment]
you can go ahead with this issue.
