### ISSUE TITLE
About Section

### ISSUE THREAD

**Issue by Preetesh21** [akshitagupta15june/lane_detection_opencv#40]
In the About Section, there are a few grammatical errors. I know it is a very trivial issue so it's ok if the owner does not pay much heed to the issue.

Corrected Version---
The lane detection has proved to be an efficient technique to prevent accidents in Intelligent Transportation Systems. The review on lane detection has shown that most of the researchers have neglected the problem of the fog and noise in images. Thus noise and fog may reduce the accuracy of the existing systems.

**Comment by Mehrapi** [comment]
Hallo, I have sent a PR for this, please let me know if you have problem accessing it. Thank you.
