### ISSUE TITLE
Develop a Python GUI for displaying Results. 

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/lane_detection_opencv#47]
Develop a Python GUI for displaying Results.
A Interactive GUI application using python (Tkinter) to show results

**Comment by Vrindagupta6828** [comment]
@akshitagupta15june Please assign me this issue.

**Comment by akshitagupta15june** [comment]
Join Discord channel for discussion.
discord.gg/qr8d7thz

**Comment by Vrindagupta6828** [comment]
@akshitagupta15june please assign

**Comment by Vrindagupta6828** [comment]
@akshitagupta15june It is showing invalid invite. Invite has expired.

**Comment by anishkabhatia** [comment]
What kind of a GUI are you looking for? What all should it contain?

**Comment by akshitagupta15june** [comment]
gui will contain a button of capturing live and a display showing the results or output.
Gui is required so that the output can be displayed externally.
