### ISSUE TITLE
 Image Thresholding (Extract lane from image)

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/lane_detection_opencv#5]
Road  image is provide , try to extract lane from road.
![lanewithout](https://user-images.githubusercontent.com/57909583/85250888-6f516500-b475-11ea-81fd-2cdee14be580.png)

**Comment by akshitagupta15june** [comment]
Provide PR after Detection

**Comment by Anujg935** [comment]
This is an additional image on which you can work on as working on this image will be easy for you.
[solidWhiteRight.jpg](https://raw.githubusercontent.com/jokla/jokla.github.io/master/images/post/2017-03-10-lane-detection/solidWhiteRight.jpg)

**Comment by akshitagupta15june** [comment]
ISSUE CLOSED
