### ISSUE TITLE
Recognition-using-CNN

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/lane_detection_opencv#55]

**Comment by Halix267** [comment]
Can I give it a try? @akshitagupta15june

**Comment by akshitagupta15june** [comment]
Yes

**Comment by Halix267** [comment]
So can u brief me what I have to do in this issue.... Means I have to detect only lanes or somethings else also

**Comment by akshitagupta15june** [comment]
This issue is focusing on lanes.

**Comment by Halix267** [comment]
Ok @akshitagupta15june . Can u check the pr also , I have generated it in Face -X project . If any improvement needed in that PRs than tell me I will try to fix them also .

**Comment by akshitagupta15june** [comment]
Yes i will be checking those prs 
But it will be great if you add a readme also in that merged pr.
