### ISSUE TITLE
Adding Environment details in ISSUE_TEMPLATE.md

### ISSUE THREAD

**Issue by Purvanshsingh** [akshitagupta15june/lane_detection_opencv#59]
**Is your feature request related to a problem? Please describe.**
Without knowing the exact environment details it is hard to reproduce the error to rectify it.

**Describe the solution you'd like**
To add an environment Section in the ISSUE_TEMPLATE.md

**Describe alternatives you've considered**

**Approach to be followed (optional)**
Adding the environment section in which the user has to provide:
OS details
pip version
python version

**Additional context**

**Comment by akshitagupta15june** [comment]
ok i am assigning it to u.
are u a dwoc participant?

**Comment by Purvanshsingh** [comment]
> ok i am assigning it to u.
> are u a dwoc participant?

yes. :-)

**Comment by akshitagupta15june** [comment]
you are dwoc or swoc participant?

**Comment by Purvanshsingh** [comment]
Swoc
