### ISSUE TITLE
Homography to get birds eye view of lane.

### ISSUE THREAD

**Issue by akshitagupta15june** [akshitagupta15june/lane_detection_opencv#67]
A Homography is a transformation ( a 3×3 matrix ) that maps the points in one image to the corresponding points in the other image. Figure 1 : Two images of a 3D plane ( top of the book ) are related by a Homography.

![image](https://user-images.githubusercontent.com/57909583/103274717-51e2f200-49e8-11eb-9c2f-4c31732eaf61.png)

**Comment by hritik5102** [comment]
Hello @akshitagupta15june, please assign this issue to me, I want to work on it.

**Comment by akshitagupta15june** [comment]
Ok assigning it to u @hritik5102
