### ISSUE TITLE
Adding Environment details in Bug_request.md

### ISSUE THREAD

**Issue by Purvanshsingh** [akshitagupta15june/lane_detection_opencv#71]
**Is your feature request related to a problem? Please describe.**
Without knowing the exact environment details it is hard to reproduce the error to rectify it.

**Describe the solution you'd like**
To add an environment Section in the Bug_request.md

**Approach to be followed (optional)**
Adding the environment section in which the user has to provide:
OS details
pip version
python version

Additional context

**Comment by akshitagupta15june** [comment]
ok great you can work on it
