### ISSUE TITLE
Updating README with Probabilistic Hough Transform information

### ISSUE THREAD

**Issue by rsrkpatwari1234** [akshitagupta15june/lane_detection_opencv#77]
**Describe the bug**
The README describes the usage of hough transform in the lane detection module.However, the optimised version of hough transform called probabilistic hough transform is used. There is lot of diference between the two algorithms.

**To Reproduce**
1.  Adding information about probabilistic hough transform in readme
2.  explaining in short why using this version instead of normal hough transform
3.  using 2 diagrams to compare the behaviour of the two algorithms
4.  explaning the importance of values of minLineLength and  maxLineGap in the HoughLinesP() function which basically differs it from normal HoughLines() opencv function

**Comment by rsrkpatwari1234** [comment]
@akshitagupta15june please assign me this issue under nwoc and update my score if the issue seems appropriate to you

**Comment by rsrkpatwari1234** [comment]
@akshitagupta15june please assign this issue to me under nwoc

**Comment by akshitagupta15june** [comment]
ok @rsrkpatwari1234
