### ISSUE TITLE
Show FPS(Frame Per Second) on the side of frame. [Easy]

### ISSUE THREAD

**Issue by q-viper** [akshitagupta15june/lane_detection_opencv#81]
* Showing FPS allows us to know about the performance of our system.

**Comment by TanweerulHaque** [comment]
Can I proceed with this issue @akshitagupta15june  ??

**Comment by akshitagupta15june** [comment]
yeah assigning you

**Comment by TanweerulHaque** [comment]
@akshitagupta15june Please review the PR sent.

**Comment by akshitagupta15june** [comment]
your pr will be reviewed soon
